---
name: Deploy API Docs - 2.x

on:
  push:
    branches:
      - 2.x
  repository_dispatch:
    types: ['build']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@apps.cakephp.org:22/api-4'
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
